### ISSUE TITLE
MyQ Not Loading garage doors or gate

### ISSUE THREAD

**Issue by PaulStraten** [Goose66/myq-polyglotv2#10]
The nodeserver loaded to Universal Devices Polisy and ISY994 but it does not show the nodes for my 2 garage doors and gate opener.

See attached log file.
[MyQ_logs_3-9-2021_80505_PM.zip](https://github.com/Goose66/myq-polyglotv2/files/6112642/MyQ_logs_3-9-2021_80505_PM.zip)

**Comment by Goose66** [comment]
Did you click the "Discover Devices" button in the controller node? See the README.MD, specifically item # 6 in the instructions:
`6. Once the MyQ Service node appears in ISY994i Adminstative Console, click "Discover Devices" to load nodes for the gateways, garage door openers, and light modules configured in your account.`
