### ISSUE TITLE
Is an update to the latest API planned?

### ISSUE THREAD

**Issue by psmith3** [Goose66/myq-polyglotv2#4]
Chamberlain updated their API last month and this build no longer works. Is there plans to update it or is it dead?

**Comment by Goose66** [comment]
Mine is still working for my LiftMaster doors and MyQ gateway. Just tested it 30 seconds ago.

**Comment by psmith3** [comment]
Good to here! I Maybe it is my custom parameters that are not set right. Are the custom parameter keys “username” and “password"?

**Comment by psmith3** [comment]
I figured out my issue. I did not do Step 6 to discover the nodes. Once I did, it loaded everything up. One reason I did not do that was because it says the nodeserver is offline when it actually is not. I have restarted the polyglot server and the ISY and that never changes. Any idea there?
![image](https://user-images.githubusercontent.com/14373163/70851873-8d079700-1e60-11ea-8914-765d0b92a55e.png)

**Comment by Goose66** [comment]
The "NodeServer Online" driver value (ST of Controller Node) has always been handled by Polyglot, and not by the nodeserver itself. Perhaps this feature has been removed at some point in the later versions of Polyglot, but it still works (poorly) on my installed version.

**Comment by Goose66** [comment]
I am planning to update this nodeserver to support MyQ lights and be cloud-poly compatible soon (maybe over Christmas holidays). I will try and remember to also add an initial setting of the NodeServer Online (ST driver) value to True in the Controller startup code.

**Comment by psmith3** [comment]
> I am planning to update this nodeserver to support MyQ lights and be cloud-poly compatible soon (maybe over Christmas holidays). I will try and remember to also add an initial setting of the NodeServer Online (ST driver) value to True in the Controller startup code.

Thanks
